name: Rails Tests

on:
  pull_request:
    branches:
      - 'develop'
      - 'master'
  push:
    branches:
      - 'develop'
      - 'master'
jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          gem install rubocop
      - name: Run linters
        run: |
          rubocop
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_PASSWORD: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Create database.yml
        run: |
          cp config/database.yml.example config/database.yml
      - name: Setup test database
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: postgres://postgres:@localhost:5432/test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        run: |
          bundle exec rspec
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: postgres://postgres:@localhost:5432/test
